In [48]:
testDataDict = {
        'body_acc_x_mean': [],
        'body_acc_y_mean': [],
        'body_acc_z_mean': [],
        'body_acc_x_std': [],
        'body_acc_y_std': [],
        'body_acc_z_std': [],
        'body_acc_x_max': [],
        'body_acc_y_max': [],
        'body_acc_z_max': [],
        'body_acc_x_min': [],
        'body_acc_y_min': [],
        'body_acc_z_min': [],
        'body_acc_x_energy': [],
        'body_acc_y_energy': [],
        'body_acc_z_energy': [],
        'body_acc_x_iqr': [],
        'body_acc_y_iqr': [],
        'body_acc_z_iqr': [],
        'body_acc_x_sma': [],
        'body_acc_y_sma': [],
        'body_acc_z_sma': [],
        'body_acc_x_mad': [],
        'body_acc_y_mad': [],
        'body_acc_z_mad': [],
        'body_acc_x_amplitude': [],
        'body_acc_y_amplitude': [],
        'body_acc_z_amplitude': [],

        'body_gyro_x_mean': [],
        'body_gyro_y_mean': [],
        'body_gyro_z_mean': [],
        'body_gyro_x_std': [],
        'body_gyro_y_std': [],
        'body_gyro_z_std': [],
        'body_gyro_x_max': [],
        'body_gyro_y_max': [],
        'body_gyro_z_max': [],
        'body_gyro_x_min': [],
        'body_gyro_y_min': [],
        'body_gyro_z_min': [],
        'body_gyro_x_energy': [],
        'body_gyro_y_energy': [],
        'body_gyro_z_energy': [],
        'body_gyro_x_iqr': [],
        'body_gyro_y_iqr': [],
        'body_gyro_z_iqr': [],
        'body_gyro_x_sma': [],
        'body_gyro_y_sma': [],
        'body_gyro_z_sma': [],
        'body_gyro_x_mad': [],
        'body_gyro_y_mad': [],
        'body_gyro_z_mad': [],
        'body_gyro_x_amplitude': [],
        'body_gyro_y_amplitude': [],
        'body_gyro_z_amplitude': [],

        'total_acc_x_mean': [],
        'total_acc_y_mean': [],
        'total_acc_z_mean': [],
        'total_acc_x_std': [],
        'total_acc_y_std': [],
        'total_acc_z_std': [],
        'total_acc_x_max': [],
        'total_acc_y_max': [],
        'total_acc_z_max': [],
        'total_acc_x_min': [],
        'total_acc_y_min': [],
        'total_acc_z_min': [],
        'total_acc_x_energy': [],
        'total_acc_y_energy': [],
        'total_acc_z_energy': [],
        'total_acc_x_iqr': [],
        'total_acc_y_iqr': [],
        'total_acc_z_iqr': [],
        'total_acc_x_sma': [],
        'total_acc_y_sma': [],
        'total_acc_z_sma': [],
        'total_acc_x_mad': [],
        'total_acc_y_mad': [],
        'total_acc_z_mad': [],
        'total_acc_x_amplitude': [],
        'total_acc_y_amplitude': [],
        'total_acc_z_amplitude': [],
}

colNames = ['body_acc_x','body_acc_y','body_acc_z','body_gyro_x','body_gyro_y','body_gyro_z','total_acc_x','total_acc_y','total_acc_z']

In [49]:
import sys
import os
import pandas as pd

notebook_dir = os.getcwd()
data_dir = os.path.abspath(os.path.join(notebook_dir, ".."))
sys.path.append(data_dir)

from processingFunctions import *

csv_path = os.path.join(os.getcwd(), "mockData.csv")

In [50]:
df = pd.read_csv(csv_path)
df.dropna(inplace=True)
df["total_acc_x"] = df["body_acc_x"]
df["total_acc_y"] = df["body_acc_y"]
df["total_acc_z"] = df["body_acc_z"]
df.head()

,timestamp,body_acc_x,body_acc_y,body_acc_z,body_gyro_x,body_gyro_y,body_gyro_z,total_acc_x,total_acc_y,total_acc_z
2,1745415453164,-0.088585,0.646435,9.557953,-0.002673,-0.004123,-0.000458,-0.088585,0.646435,9.557953
3,1745415453345,-0.119710,0.636858,9.574712,0.000993,-0.001680,0.000764,-0.119710,0.636858,9.574712
4,1745415453527,-0.100556,0.641646,9.565135,0.000993,-0.001680,-0.000458,-0.100556,0.641646,9.565135
7,1745415453888,-0.079009,0.639252,9.608231,0.000382,-0.000458,0.000764,-0.079009,0.639252,9.608231
8,1745415454068,-0.079009,0.651223,9.589077,0.001604,-0.002291,-0.000458,-0.079009,0.651223,9.589077

In [51]:
df["body_acc_x"] = filterAcceleration(df["body_acc_x"])
df["body_acc_y"] = filterAcceleration(df["body_acc_y"])
df["body_acc_z"] = filterAcceleration(df["body_acc_z"])
df.head()

,timestamp,body_acc_x,body_acc_y,body_acc_z,body_gyro_x,body_gyro_y,body_gyro_z,total_acc_x,total_acc_y,total_acc_z
2,1745415453164,0.001219,0.005686,-0.005870,-0.002673,-0.004123,-0.000458,-0.088585,0.646435,9.557953
3,1745415453345,0.005126,0.009367,0.000348,0.000993,-0.001680,0.000764,-0.119710,0.636858,9.574712
4,1745415453527,0.005263,0.013094,0.010760,0.000993,-0.001680,-0.000458,-0.100556,0.641646,9.565135
7,1745415453888,0.007533,0.014243,0.023347,0.000382,-0.000458,0.000764,-0.079009,0.639252,9.608231
8,1745415454068,-0.000453,0.015789,0.023155,0.001604,-0.002291,-0.000458,-0.079009,0.651223,9.589077

In [52]:
window_length = 128
overlap_pct = 0.5
shift = int(window_length * overlap_pct)

for i in range(0, len(df) - window_length, shift):
    window = df.iloc[i:i+window_length]
    for name in colNames:
        signal = window[name].values
        testDataDict[name + "_mean"].append(np.mean(signal))
        testDataDict[name + "_std"].append(np.std(signal))
        testDataDict[name + "_max"].append(np.max(signal))
        testDataDict[name + "_min"].append(np.min(signal))
        testDataDict[name + "_energy"].append(findEnergy(signal))
        testDataDict[name + "_iqr"].append(findQuantile(signal))
        testDataDict[name + "_sma"].append(findSMA(signal))
        testDataDict[name + "_mad"].append(findMad(signal))
        testDataDict[name + "_amplitude"].append(findAmplitude(signal))

testDataDF = pd.DataFrame(testDataDict)
testDataDF.to_csv('processedTestDF.csv', index=False)
testDataDF.sample()

,body_acc_x_mean,body_acc_y_mean,body_acc_z_mean,body_acc_x_std,body_acc_y_std,body_acc_z_std,body_acc_x_max,body_acc_y_max,body_acc_z_max,body_acc_x_min,...,total_acc_z_iqr,total_acc_x_sma,total_acc_y_sma,total_acc_z_sma,total_acc_x_mad,total_acc_y_mad,total_acc_z_mad,total_acc_x_amplitude,total_acc_y_amplitude,total_acc_z_amplitude
9,0.099618,-0.270611,0.295396,1.910045,2.243146,2.069077,7.784545,7.393463,3.079975,-2.706975,...,1.683124,294.651711,279.343183,1098.346316,1.476025,1.772906,0.824803,0.367504,0.332562,0.499618